import {
  DOMAIN_PACK_SCHEMA_VERSION,
  type DomainPackV0,
  type Entity,
  type ExtractionContractEntry,
  type OutputSpecificationEntry,
  type Rule,
} from './index.js';

export function minimalRule(id: string, overrides?: Partial<Rule>): Rule {
  return {
    id,
    primitive: 'REQUIRE',
    entityIds: [],
    factIds: [],
    authorityRefIds: [],
    ...overrides,
  };
}

export function minimalEntity(id: string, overrides?: Partial<Entity>): Entity {
  return { id, grammarType: 'Party', ...overrides };
}

export function minimalOutputSpecification(
  id: string,
  overrides?: Partial<OutputSpecificationEntry>,
): OutputSpecificationEntry {
  return {
    id,
    audience: 'professional',
    claimTypes: [
      {
        id: 'claim-finding-001',
        label: 'Validated finding claim',
        supportRequirements: [
          { kind: 'extraction', factId: 'fact-001', minCount: 1 },
          { kind: 'rule_outcome', ruleId: 'rule-001', allowedRuleOutcomes: ['FIRED'], minCount: 1 },
        ],
        permitsUndetermined: false,
        sectionIds: ['section-findings'],
      },
    ],
    sections: [
      {
        id: 'section-findings',
        sectionType: 'FINDINGS_LIST',
        order: 0,
        claimTypeIds: ['claim-finding-001'],
        sourceFactIds: ['fact-001'],
        sourceRuleIds: ['rule-001'],
        sourceEntityIds: ['entity-001'],
        fields: [
          { id: 'finding-claim', source: 'claim', claimTypeId: 'claim-finding-001', required: true },
        ],
        questionIds: [],
        documentTypeIds: [],
        missingFactIds: [],
        evidenceRequired: true,
        cardinality: { minItems: 0 },
        emptyState: 'show_empty',
        narrativePermissions: {
          allowed: true,
          requiresClaimRefs: true,
          permitsUncertaintyStatements: false,
        },
        professionalOnly: false,
      },
      {
        id: 'section-entities',
        sectionType: 'ENTITY_TABLE',
        order: 1,
        sourceEntityIds: ['entity-001'],
        fields: [{ id: 'entity-label', source: 'entity', entityId: 'entity-001', required: true }],
        claimTypeIds: [],
        sourceFactIds: [],
        sourceRuleIds: [],
        questionIds: [],
        documentTypeIds: [],
        missingFactIds: [],
        evidenceRequired: false,
        cardinality: { minItems: 0 },
        emptyState: 'omit',
        narrativePermissions: { allowed: false, requiresClaimRefs: true, permitsUncertaintyStatements: false },
        professionalOnly: false,
      },
      {
        id: 'section-timeline',
        sectionType: 'TIMELINE',
        order: 2,
        sourceFactIds: ['fact-001'],
        timeModelId: 'tm-001',
        fields: [{ id: 'event-date', source: 'fact_extraction', factId: 'fact-001', required: true }],
        claimTypeIds: [],
        sourceRuleIds: [],
        sourceEntityIds: [],
        questionIds: [],
        documentTypeIds: [],
        missingFactIds: [],
        evidenceRequired: true,
        cardinality: { minItems: 0 },
        emptyState: 'omit',
        narrativePermissions: { allowed: false, requiresClaimRefs: true, permitsUncertaintyStatements: false },
        professionalOnly: false,
      },
      {
        id: 'section-questions',
        sectionType: 'QUESTION_LIST',
        order: 3,
        questionIds: ['q-001'],
        fields: [{ id: 'question-text', source: 'question', questionId: 'q-001', required: true }],
        claimTypeIds: [],
        sourceFactIds: [],
        sourceRuleIds: [],
        sourceEntityIds: [],
        documentTypeIds: [],
        missingFactIds: [],
        evidenceRequired: false,
        cardinality: { minItems: 0 },
        emptyState: 'omit',
        narrativePermissions: { allowed: false, requiresClaimRefs: true, permitsUncertaintyStatements: false },
        professionalOnly: false,
      },
      {
        id: 'section-doc-requests',
        sectionType: 'DOCUMENT_REQUESTS',
        order: 4,
        documentTypeIds: ['doc-type-001'],
        missingFactIds: ['fact-001'],
        fields: [
          { id: 'requested-doc', source: 'document_type', documentTypeId: 'doc-type-001', required: true },
        ],
        claimTypeIds: [],
        sourceFactIds: [],
        sourceRuleIds: [],
        sourceEntityIds: [],
        questionIds: [],
        evidenceRequired: false,
        cardinality: { minItems: 0 },
        emptyState: 'omit',
        narrativePermissions: { allowed: false, requiresClaimRefs: true, permitsUncertaintyStatements: false },
        professionalOnly: false,
      },
      {
        id: 'section-snapshot',
        sectionType: 'CASE_SNAPSHOT',
        order: 5,
        sourceFactIds: ['fact-001'],
        fields: [{ id: 'snapshot-date', source: 'fact_extraction', factId: 'fact-001', required: true }],
        claimTypeIds: [],
        sourceRuleIds: [],
        sourceEntityIds: [],
        questionIds: [],
        documentTypeIds: [],
        missingFactIds: [],
        evidenceRequired: true,
        cardinality: { minItems: 1, maxItems: 1 },
        emptyState: 'show_message',
        emptyMessageKey: 'snapshot.empty',
        narrativePermissions: { allowed: false, requiresClaimRefs: true, permitsUncertaintyStatements: false },
        professionalOnly: false,
      },
    ],
    ...overrides,
  };
}

export function minimalExtractionContract(
  id: string,
  factId: string,
  overrides?: Partial<ExtractionContractEntry>,
): ExtractionContractEntry {
  return {
    id,
    factId,
    definition: `Reader-facing definition for ${factId}`,
    expectedType: 'string',
    cardinality: 'exactly_one',
    evidence: { required: true, minCount: 1 },
    positiveExamples: [],
    negativeExamples: [],
    documentTypeIds: [],
    vocabularyRefs: [],
    identityHints: [],
    phrasingConstraints: [],
    unitRequired: false,
    ...overrides,
  };
}

export function minimalDomainPack(overrides?: Partial<DomainPackV0>): DomainPackV0 {
  return {
    schemaVersion: DOMAIN_PACK_SCHEMA_VERSION,
    packId: 'pack-neutral-001',
    domainId: 'domain-neutral',
    packVersion: '0.1.0',
    scope: 'synthetic-test-scope',
    jurisdiction: 'TEST-JURISDICTION',
    dependencies: { extends: [], overlay: [], shared: [] },
    authorityReferences: [],
    documentTypes: [],
    vocabulary: [],
    entities: [],
    facts: [],
    extractionContracts: [],
    outputSpecifications: [],
    composition: {},
    timeModels: [],
    identityStrategies: [],
    rules: [],
    questions: [],
    capabilityRequirements: [],
    fixtureReferences: [],
    provenanceReferences: [],
    ...overrides,
  };
}
